eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
server:
  port: 8082
spring:
  application:
    name: spring-boot-admin
zuul:
   sensitiveHeaders:
management.security.enabled: false
spring.boot.admin.routes.endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream,loggers

spring.boot.admin.turbine:
  clusters: default
  location: turbine
#spring.boot.admin.discovery.management.context-path: /admin
