eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
server:
  port: 8082
spring:
  application:
    name: spring-boot-admin
zuul:
   sensitiveHeaders:
#spring.boot.admin.discovery.management.context-path: /admin